#pragma once
#pragma once
#include "SFML/Graphics.hpp"
#include <string>
#include <iostream>
#include <fstream>
#include <sstream>
#include <functional>
#include <map>
#include <vector>
#include <memory>
